### ISSUE TITLE
Sorting issue (play tab)

### ISSUE THREAD

**Issue by EatThePath** [KnossosNET/Knossos.NET#147]
I'm unclear exactly what is happening here, but Knossos is not *quite* sorting by name at startup. My KNDN starts up looking like:
![image](https://github.com/KnossosNET/Knossos.NET/assets/4766365/ba054f6a-6ef4-4336-9792-1a15b1fe6480)
Now in this state I can't click on 'Sort by Name', so I assume the tool expects it to be sorted by name right now. But if I click to another option and then back to name, it becomes:
![image](https://github.com/KnossosNET/Knossos.NET/assets/4766365/15f92803-e432-433a-ba59-5b5d25502065)

at first I thought it might be initially sorted by folder names, but war of neptune wouldn't be up there if it was. My best guess is that it is not sorting by the right *version's* name initially, the release versions of Warmachine are named "Warmachine" and the unreleased dev versions are named "!Warmachine" to pop to the top for my own convenience, and I have local copies of both versions.  The initial sorting is consistent with the first and the explicitly sorted by name is consistent with the later.

**Comment by JohnAFernandez** [comment]
I think I'm seeing the behavior on my end.  Just creating a mod ABC, BCD, CDE, then renaming BCD to !BCD seems to trigger !BCD being sorted in the middle until the screen is switched back to sort by name.

**Comment by JohnAFernandez** [comment]
Afaict, your understanding of the problem was partially correct.  But Knossos was also trying to set it to Sort by name on start and invariably failing because of a load order issue and a faulty check.  See the PR for more detail.
