### ISSUE TITLE
[FR] sorted dev tab

### ISSUE THREAD

**Issue by EatThePath** [KnossosNET/Knossos.NET#148]
The dev tab appears to be sorted via folder structure; mods of a given TC are grouped under that TC, and otherwise everything is sorted by folder name, and thus mod ID. When you have enough mods this can make it hard to intuit where a mod is going to be and jump to it when the list is long enough, and at 28 mods I've definitely crossed that threshold personally.

I would prefer to have two other options for sorting, display name and most recently launched. I would also like it to remember which option is in use between sessions, something that is not currently true of the other tab's sorting options.

**Comment by JohnAFernandez** [comment]
I haven't looked into this yet, but I thought I had sorting behavior persist on the Play and Explore tabs.
