### ISSUE TITLE
Trying to create a mod with solaris as a parent gives errors

### ISSUE THREAD

**Issue by MoerasGrizzly** [KnossosNET/Knossos.NET#149]
Specifically:
![afbeelding](https://github.com/KnossosNET/Knossos.NET/assets/9599230/fd7634bc-8d54-4068-bc29-64dffc1cd531)

I'm suspecting that using something other then retail FS2 as a parent mod might mean that the parent mod is not loaded as a dependency properly.

**Comment by JohnAFernandez** [comment]
Is this on RC9 or RC10?

**Comment by MoerasGrizzly** [comment]
It's actually fine on RC10, as it turns out. I was sure I had upgraded...
