### ISSUE TITLE
Selection status should consider whether a newly added package is recommended

### ISSUE THREAD

**Issue by Goober5000** [KnossosNET/Knossos.NET#156]
When I updated Scroll from version 1.10 to version 1.11, I added a new recommended package, `anims`.  (This was split off from the existing required package `misc`.)  However, this new package was not selected by default when I used Knossos.NET to update Scroll on a different computer.

Expected behavior: Any newly added packages with "recommended" status should be selected by default.  Old Knossos notifies the user with the following message:
> This mod has new optional or recommended packages. Please take a look and select the packages you want. You can click on any entry to receive more information.

Here is what is displayed on Knossos.NET:

![selection_status](https://github.com/KnossosNET/Knossos.NET/assets/1878523/ab8526a5-f249-4e2f-b27a-41d755c3623f)

**Comment by JohnAFernandez** [comment]
So, I think, yes, Knossos should check for a package in a previously installed version.  This is going to take a solid amount of effort, though.
