### ISSUE TITLE
Mod compression function compresses unsupported mods when i set it to "mod support"

### ISSUE THREAD

**Issue by kotenok2000** [KnossosNET/Knossos.NET#169]
Mod compression function compresses "Adversary" when i set it to "mod support". 
Adversary runs FSO 19.0 by default so it should be exempt from compression.
![image](https://github.com/KnossosNET/Knossos.NET/assets/8822292/31474ee7-fe18-4366-9a72-2f72ec05a521)
![image](https://github.com/KnossosNET/Knossos.NET/assets/8822292/42d6f204-2efa-4a6c-adc6-f2e716143b2f)

![image](https://github.com/KnossosNET/Knossos.NET/assets/8822292/1d0a3c75-7e72-41dd-b242-1bca1bbc3800)

**Comment by kotenok2000** [comment]
![image](https://github.com/KnossosNET/Knossos.NET/assets/8822292/5f565e19-6d6e-489a-b227-4513852c2da9)

**Comment by JohnAFernandez** [comment]
Ok, I'm putting it on the 1.1 milestone
