### ISSUE TITLE
FR: Clean Nightlies button in Engine tab

### ISSUE THREAD

**Issue by MjnMixael** [KnossosNET/Knossos.NET#172]
I'm sure there are a lot of developers like me that download a new nightly almost every day. It'd be handy to have a single button that can clean them up.. say delete all nightlies leaving RCs and Stable intact. With each stable release and a single click I can save a bunch of disk space rather than having to do it all manually.

**Comment by JohnAFernandez** [comment]
Doesn't sound too hard, tbh.  I'll just make sure there's some kind of confirmation. I'll put it on the 1.2 milestone.
