### ISSUE TITLE
Underscores do not show up in GUI

### ISSUE THREAD

**Issue by wookieejedi** [KnossosNET/Knossos.NET#178]
Throughout the Dev tab, and possibly other locations, underscore characters are not displayed. For example, in a Mod ID I have a mod that has an underscore in the Mod ID, and it is present in the json file `FotG_R`, but in KNet it simply is shown as `FotGR`. Similarly, if I make a mod package, I can type an underscore into the package name, and it makes the folder name with the underscore, but it does not display the underscore in the GUI.

**Comment by notimaginative** [comment]
Should be fixed in #179 but you might want to give that PR a try just to be sure I didn't miss anything.
