### ISSUE TITLE
Engine list should update after downloading new engine builds

### ISSUE THREAD

**Issue by MjnMixael** [KnossosNET/Knossos.NET#224]
It seems right now that after downloading a new engine build you have to force a mod list refresh to get those builds to show in the developer engine builds list and be able to select them. It'd be handy to have this a little more streamlined so I can download a build and then immediately select it.

**Comment by Shivansps** [comment]
This is a bug, i might try to push it with v1.2.4 if i have enoght time.

**Comment by Shivansps** [comment]
Just to clearify, because i may had seem different issues. You can post me a picture of the list thats dosent display the build until you do a refresh. I just want to confirm i saw the problem in the same place as you.

**Comment by MjnMixael** [comment]
<img width="694" alt="image" src="https://github.com/user-attachments/assets/5d967b91-cff7-457e-a189-bf7b8fd9c071">
This one
