### ISSUE TITLE
UI Text is shifted up

### ISSUE THREAD

**Issue by topas-rec** [KnossosNET/Knossos.NET#71]
Hello,

I am seeing that the text is shifted up in the UI on arch linux:
It is cut off at the top where is has contact to the UI elements. See the `PXO` entry in this screenshot.
![image](https://github.com/KnossosNET/Knossos.NET/assets/20391449/a43fc4d2-c3d8-44d6-b057-361aaec4560b)

Do you have an idea why or how to fix that?

Best wishes

**Comment by JohnAFernandez** [comment]
So, unfortunately, Avalalonia UI doesn't seem to deal with multiplatform differences in font placement very well.  Moving text around within buttons often ends up with some cut off text like this on another platform.  This happened when I was working on cleaning up the download list.  I don't think we can currently fix it.

**Comment by Shivansps** [comment]
Yeah, we have to report all of these differences to Avalonia devs at some point.

**Comment by Shivansps** [comment]
It is interesting that this does not seem to happen on ARM64 Ubuntu.

**Comment by topas-rec** [comment]
Can you test this on other distros, too?
I can maybe do a test on manjaro, but since it is based on arch I don't expect any difference.
But I have a mint live USB key and it should work without a reboot. Maybe I can try that.

**Comment by topas-rec** [comment]
I found this issue in the SDL version of xonotic on the same system, too.
It doesn't happen that often, but it was there one or two times.

**Comment by wookieejedi** [comment]
Ideally #127 will fix this once merged.

**Comment by JohnAFernandez** [comment]
@topas-rec is this fixed on Main with 127 merged?

**Comment by topas-rec** [comment]
Sorry for being late with testing I had troubles building this ([caused by external software](https://gitlab.archlinux.org/archlinux/packaging/packages/pacman/-/issues/19)).

With v1.1.0 the shifted text is gone. Thanks for your help!
