### ISSUE TITLE
Mod Decompression percentage seems to get stuck at 99% despite being done

### ISSUE THREAD

**Issue by JohnAFernandez** [KnossosNET/Knossos.NET#81]
Mod Decompression percentage seems to get stuck at 99% despite being done.  This was reported once on discord and I just saw it on my computer myself.  This is a UI only issue.  And only happens sometimes.

**Comment by JohnAFernandez** [comment]
After updating my master branch and installing Bem Cavalgar, I did not see this bug occur.  I will try again with a larger mod.

**Comment by Shivansps** [comment]
Its probably just random, probably missing to catch the last read on ProgressStream for some reason. 

Generally when i know i completed the progress bar thing i usually set currentprogress = maxprogress just to be sure, maybe i missed one somewhere.
