### ISSUE TITLE
Retail FS2 not getting recognized on Linux

### ISSUE THREAD

**Issue by JohnAFernandez** [KnossosNET/Knossos.NET#87]
LSDNinja is reporting that his Linux KNet install is showing retail FS2 as installed but he is unable to download mods based on FS2.

**Comment by notimaginative** [comment]
I managed to reproduce this problem. In some cases with the retail vps the filenames are mixed case. In particular, `root_fs2.vp` is often `Root_fs2.vp`. On a case sensitive filesystem, like Linux tends to use, it will cause the retail install check to fail in `FolderSearchRecursive()`. When that happens the retail mod is shown as installed but the Explore page will only list TCs.
